name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub commits
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.commits) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: get commit message
        id: commit
        run: |
          echo ::set-output name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run: echo $commitmsg
        env:
          commitmsg: ${{ steps.commit.outputs.commitmsg }}
      - name: Skip
        if: contains(github.event.commits[0].message, '[skip tests]') == false
        run: echo Skip
      - name: Don't skip
        run: echo Don\'t skip
